# Generated by ChatGPT

import numpy as np
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression

# Data excluding (0,0)
x_values = [0.1, 0.125, 0.15, 0.175, 0.2, 0.225, 0.25, 0.275] # normalized voltage
y_values = [0.73, 0.88, 1.02, 1.15, 1.29, 1.4, 1.52, 1.67] # velocity

# Linear Regression
linear_reg_model = LinearRegression()
linear_reg_model.fit(np.array(x_values).reshape(-1, 1), y_values)
y_linear_fit = linear_reg_model.predict(np.array(x_values).reshape(-1, 1))

# Linear Equation: y = mx + b
linear_equation = f"y = {linear_reg_model.coef_[0]:.4f}x + {linear_reg_model.intercept_:.4f}"

# Plotting the original data and the linear regression curve
plt.figure(figsize=(10, 6))

# Plotting the original data points
plt.plot(x_values, y_values, marker='o', linestyle='-', color='g', label='Data Points')

# Plotting the linear regression curve
plt.plot(x_values, y_linear_fit, linestyle='--', color='r', label=f'Linear: {linear_equation}')

# Adding labels and title
plt.xlabel('X values')
plt.ylabel('Y values')
plt.title('Linear Regression without (0,0)')

# Displaying the legend
plt.legend()

# Displaying the plot
plt.grid(True)
plt.show()
